// Detect or generate a Dockerfile for a checked-out repo, driven by the
// project's framework preset. Returns { mode, dockerfile, internalPort }.
import { existsSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { getPreset, detectFramework, translateCmd } from './presets.js';

export function resolveBuild(project, dir) {
  const wanted = project.dockerfile_path || 'Dockerfile';
  const repoDockerfile = join(dir, wanted);
  const fallbackPort = project.internal_port || 3000;

  // Force the repo Dockerfile.
  if (project.build_method === 'dockerfile') {
    if (!existsSync(repoDockerfile)) throw new Error(`build_method=dockerfile but ${wanted} not found in repo`);
    return { mode: 'dockerfile', dockerfile: wanted, internalPort: fallbackPort };
  }

  // Auto: prefer a repo Dockerfile when present.
  if ((project.build_method === 'auto' || !project.build_method) && existsSync(repoDockerfile)) {
    return { mode: 'dockerfile', dockerfile: wanted, internalPort: fallbackPort };
  }

  // Otherwise generate from the framework preset.
  return generate(project, dir);
}

function detectPackageManager(dir) {
  if (existsSync(join(dir, 'pnpm-lock.yaml'))) return 'pnpm';
  if (existsSync(join(dir, 'yarn.lock'))) return 'yarn';
  return 'npm';
}

function readPkg(dir) {
  try {
    return JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
  } catch {
    return {};
  }
}

function defaultInstall(pm, dir) {
  if (pm === 'pnpm') return 'corepack enable && pnpm install --frozen-lockfile || pnpm install';
  if (pm === 'yarn') return 'yarn install --frozen-lockfile || yarn install';
  return existsSync(join(dir, 'package-lock.json')) ? 'npm ci || npm install' : 'npm install';
}

function generate(project, dir) {
  const pkg = readPkg(dir);
  let frameworkId = project.framework && project.framework !== 'auto' ? project.framework : detectFramework(pkg);
  let preset = getPreset(frameworkId);

  // A 'dockerfile' framework with no repo Dockerfile falls back to detection.
  if (preset.type === 'dockerfile') {
    frameworkId = detectFramework(pkg);
    preset = getPreset(frameworkId);
  }

  const pm = detectPackageManager(dir);
  let install = project.install_command || translateCmd(preset.install || defaultInstall(pm, dir), pm);
  // `npm ci` requires a lockfile — fall back to `npm install` when it's absent.
  if (!project.install_command && pm === 'npm' && /^npm ci\b/.test(install) && !existsSync(join(dir, 'package-lock.json'))) {
    install = 'npm install';
  }
  const build = project.build_command || translateCmd(preset.build || '', pm);

  if (preset.type === 'static') {
    return generateStatic({ project, dir, preset, install, build, frameworkId });
  }
  return generateNode({ project, dir, pkg, preset, pm, install, build, frameworkId });
}

function generateNode({ project, dir, pkg, preset, pm, install, build, frameworkId }) {
  const port = project.internal_port || preset.port || 3000;
  const hasStart = pkg.scripts && pkg.scripts.start;
  const start =
    project.start_command ||
    translateCmd(preset.start || (hasStart ? 'npm start' : 'node index.js'), pm);

  const buildStep = build ? `RUN ${build}` : '# no build step';

  // NOTE: NODE_ENV is set to production only AFTER install+build, otherwise
  // `npm ci`/`npm install` skip devDependencies (vite, typescript, tailwind, …)
  // and the build step fails with "<tool>: not found".
  const dockerfile = `# syntax=docker/dockerfile:1
# Auto-generated by Mintaz Deploy — framework: ${frameworkId}
FROM node:20-alpine
WORKDIR /app
ENV PORT=${port}

COPY package*.json pnpm-lock.yaml* yarn.lock* ./
RUN ${install}

COPY . .
${buildStep}

ENV NODE_ENV=production
EXPOSE ${port}
CMD ${JSON.stringify(['sh', '-c', start])}
`;

  writeFileSync(join(dir, 'Dockerfile.mintaz'), dockerfile);
  return { mode: 'generated', dockerfile: 'Dockerfile.mintaz', internalPort: port, framework: frameworkId };
}

function generateStatic({ project, dir, preset, install, build, frameworkId }) {
  const output = project.output_dir || preset.output || 'dist';

  // SPA-friendly nginx config copied into the image.
  writeFileSync(
    join(dir, 'nginx.mintaz.conf'),
    `server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  location / {
    try_files $uri $uri/ /index.html;
  }
}
`
  );

  let dockerfile;
  if (build) {
    // Build in Node, serve the output folder with nginx.
    dockerfile = `# syntax=docker/dockerfile:1
# Auto-generated by Mintaz Deploy — framework: ${frameworkId} (static)
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json pnpm-lock.yaml* yarn.lock* ./
RUN ${install}
COPY . .
RUN ${build}

FROM nginx:alpine
COPY --from=build /app/${output} /usr/share/nginx/html
COPY nginx.mintaz.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
`;
  } else {
    // Plain static files, no build.
    const src = output && output !== '.' ? `${output}` : '.';
    dockerfile = `# syntax=docker/dockerfile:1
# Auto-generated by Mintaz Deploy — static HTML
FROM nginx:alpine
COPY ${src} /usr/share/nginx/html
COPY nginx.mintaz.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
`;
  }

  writeFileSync(join(dir, 'Dockerfile.mintaz'), dockerfile);
  return { mode: 'generated', dockerfile: 'Dockerfile.mintaz', internalPort: 80, framework: frameworkId };
}
